# -*- coding: utf-8 -*-
"""2 player tic tac toe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyfS_0tMrTh-nsyrYDkUUfhkC56cNdWy
"""

print('Tic Tac Toe')
print('-----------')
blockone = 1
blocktwo = 2
blockthree = 3
blockfour = 4
blockfive = 5
blocksix = 6
blockseven = 7
blockeight = 8
blocknine = 9
def gamePlayArea():
  print('_'+str(blockone)+'_|_'+str(blocktwo)+'_|_'+str(blockthree)+'_')
  print('_'+str(blockfour)+'_|_'+str(blockfive)+'_|_'+str(blocksix)+'_')
  print(' '+str(blockseven)+' | '+str(blockeight)+' | '+str(blocknine)+' ')
def Oturn():
  global blockone, blocktwo, blockthree, blockfour, blockfive, blocksix, blockseven, blockeight, blocknine
  Oturn = int(input())
  if Oturn == 1:
    blockone='O'
    gamePlayArea()
  elif Oturn == 2:
    blocktwo='O'
    gamePlayArea()
  elif Oturn == 3:
    blockthree = 'O'
    gamePlayArea()
  elif Oturn == 4:
    blockfour = 'O'
    gamePlayArea()
  elif Oturn == 5:
    blockfive = 'O'
    gamePlayArea()
  elif Oturn == 6:
    blocksix = 'O'
    gamePlayArea()
  elif Oturn == 7:
    blockseven = 'O'
    gamePlayArea()
  elif Oturn == 8:
    blockeight = 'O'
    gamePlayArea()
  elif Oturn == 9:
    blocknine = 'O'
    gamePlayArea()
  else:
    exit()

def Xturn():
  global blockone, blocktwo, blockthree, blockfour, blockfive, blocksix, blockseven, blockeight, blocknine
  Xturn = int(input())
  if Xturn == 1:
    blockone='X'
    gamePlayArea()
  elif Xturn == 2:
    blocktwo='X'
    gamePlayArea()
  elif Xturn == 3:
    blockthree = 'X'
    gamePlayArea()
  elif Xturn == 4:
    blockfour = 'X'
    gamePlayArea()
  elif Xturn == 5:
    blockfive = 'X'
    gamePlayArea()
  elif Xturn == 6:
    blocksix = 'X'
    gamePlayArea()
  elif Xturn == 7:
    blockseven = 'X'
    gamePlayArea()
  elif Xturn == 8:
    blockeight = 'X'
    gamePlayArea()
  elif Xturn == 9:
    blocknine = 'X'
    gamePlayArea()
  else:
    exit()




def checker():
  if blockone == blocktwo == blockthree:
    print('The winner is '+ blockone)
  elif blockone == blockfour == blockseven:
    print('The winner is ' + blockone)
  elif blockone == blockfive == blocknine:
    print('the winner is ' + blockone)
  elif blocktwo == blockfive == blockeight:
    print('The winner is ' + blocktwo)
  elif blockthree == blocksix == blocknine:
    print(' The winner is '+ blockthree)
  elif blockthree == blockfive == blockseven:
    print(' the winner is '+blockthree)
  elif blockfour == blockfive == blocksix:
    print('the winner is '+ blockfour)
  elif blockseven == blockeight == blocknine:
    print('the winner is '+ blockseven)
  else:
    print('-----------------------')
gamePlayArea()
Oturn()
checker()
Xturn()
checker()
Oturn()
checker()
Xturn()
checker()
Oturn()
checker()
Xturn()
checker()
Oturn()
checker()
Xturn()
checker()
Oturn()
checker()