# -*- coding: utf-8 -*-
"""A proper calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MzWFtFKi3Ggk4WnXmT-i2ND5MSKjrAZU
"""

print (" ___________")
print("| CALCULATOR|")
print(" -----------")

def initializer():
  global terms
  terms = []
  a = int(input(" Enter the number of terms your calculation has: "))
  for i in range((2*a)-1):
    b = input()
    terms.append(b)
  print(terms)
def segregator():
  global lenghtList, digits, operators
  lenghtList = len(terms)
  digits = []
  operators = []
  for i in terms:
    if terms.index(i)%2 == 0:
      digits.append(int(i))
    if terms.index(i)%2 != 0 :
      operators.append(i)
  operators.append('+')
def algorithm():
    global lengthDigits, lengthOperators, expression, answer, exp
    lengthDigits = len(digits)
    lengthOperators = len(operators)
    expression = ''
    for i in range(lengthDigits):
      expression+=str(digits[i])
      print(expression)
      expression+=operators[i]
      print(expression)
    expression+=str(0)
    print(expression)
    answer = eval(expression)
    print(answer)
    print("© Parth Sharma of 10D")




initializer()
segregator()
algorithm()