# -*- coding: utf-8 -*-
"""Caesar Encryption and Decryption

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RjLOkcGAFVC3nvZkf92o8PX1Vnyy5px
"""

alphabets = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
messagel = []
keyalpha = []
alphaindex = []
encrypted = []
decrypted = []
alphaindexdupli = []
print('ENCRYPTION AND DECRYPTION')
print('-------------------------')
print('Do you want to ')
print('1. Encrypt')
print('2. Decrypt')
choice = int(input(''))
def encrypt():
  messagel.clear()
  keyalpha.clear()
  encrypted.clear()
  decrypted.clear()
  alphaindex.clear()
  alphaindexdupli.clear()
  message = input('Enter the message: ')
  for i in message:
    messagel.append(i)
  key = int(input('Enter the key: '))
  startaplha = alphabets[key-1]
  keyalpha.append(alphabets[key-1])
  keyalpha.append(alphabets[key])
  for i in range (1,25-key):
    keyalpha.append(alphabets[key+i])
  b = 26-key
  c = 26-b
  for i in range (c):
    keyalpha.append(alphabets[i-1])
  print(alphabets)
  print(keyalpha)
  print(messagel)
  for i in messagel:
    alphaindex.append(alphabets.index(i))
  for i in alphaindex:
    encrypted.append(keyalpha[i])
  print('Encrypted message is: ')
  print(encrypted)
def decrypt():
  messagel.clear()
  keyalpha.clear()
  encrypted.clear()
  decrypted.clear()
  alphaindex.clear()
  alphaindexdupli.clear()
  a = input('Enter encrypted word: ')
  for i in a:
    messagel.append(i)
  key = int(input('Enter key: '))
  keyalpha.append(alphabets[key-1])
  keyalpha.append(alphabets[key])
  for i in range (1,25-key):
    keyalpha.append(alphabets[key+i])
  b = 26-key
  c = 26-b
  for i in range (c):
    keyalpha.append(alphabets[i-1])
  print(alphabets)
  print(keyalpha)
  for i in messagel:
    alphaindex.append(keyalpha.index(i))
  for i in alphaindex:
    decrypted.append(alphabets[i])
  print('Decrypted message is: ')
  print(decrypted)
def goAgain():
  print('Do you want to ')
  print('1. Encrypt')
  print('2. Decrypt')
  choice = int(input(''))
  checker()
def checker():
  if choice == 1:
   encrypt()
   print('Wanna go again?')
   print('1 = yes')
   print('2 = no')
   j = int(input())
   if j == 1:
    goAgain()
   else:
    exit()
  elif choice == 2:
   decrypt()
   print('Wanna go again?')
   print('1 = yes')
   print('2 = no')
   j = int(input())
   if j == 1:
    goAgain()
   else:
    exit()
checker()

